---
title: Mount Auburn Cemetery
email: transcribing@mountauburn.org
owner: Mount Auburn Cemetery
description: Established in 1831, Mount Auburn Cemetery in Cambridge, Massachusetts,
  is the first rural cemetery in the country. 19th-century records tell the story
  of the initial vision and how it is has evolved as a designed landscape and burial
  site. Including letters between its founding horticulturalists, commissions for
  works of art and buildings, trustee minutes and reports, and correspondence to and
  from the Cemetery. These pages detail all aspects of cemetery business,  the rural
  cemetery movement, and the history of American landscape management and design.
  Read our transcribing conventions <a href="https://www.fromthepage.com/mountauburncemetery/mount-auburn-tutorial-documents/demotrustees/help">here</a>.
  Visit our <a href="https://mountauburn.pastperfectonline.com/">collections database</a>
  to discover even more of our unique holdings.
plugins:
- jekyll-feed
- jekyll-remote-theme
remote_theme: mmistakes/minimal-mistakes
defaults:
- scope:
    path: ''
  values:
    layout: archive
